### ISSUE TITLE
color changing

### ISSUE THREAD

**Issue by wolfm2** [ketai/ketai.org#12]
If you have any issues with this let me know.  If i don't hear anything, I will mark it fixed in a few days.

Final fix:
Use graphicsmagick to rotate the hue on existing images.
Rotation amount is derived from a _hash_ of  http://ketailibrary.org/ketai.txt prettyVersion.
Seems to generate sane colors for the next 5 versions.

Look at c9 for the examples.

Fails:
Using date does not create a great change in colors.
css can rotate hue on images but not backgrounds
Tried in javascript and with external image tools to swap out colors in images.  Javascript was slow and both generated poor quality results.

**Comment by danielsauter** [comment]
good to go
