### ISSUE TITLE
c9 git repo untracked thumbnails

### ISSUE THREAD

**Issue by wolfm2** [ketai/ketai.org#9]
I was looking at the c9 ketai.org clone and saw several old untracked thumbnails.   Can these be deleted?
---
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        assets/thumbnails/01df6f63a2a3ed4c3e6cd4aa2d904e13.png
        assets/thumbnails/081945a257b52ea8bebb99dbee8bc34f.png
        assets/thumbnails/0a60dbd8caeccda2c2ccc42f09be8ec6.png
        assets/thumbnails/0e3bf487fba2d3b202d929f34ed79c1e.png
        assets/thumbnails/46067ca4d569ef754630f34fa3d33125.png
        assets/thumbnails/46b6c7ddb95deddf5070d5d7fd4f9f57.png
        assets/thumbnails/49c71c8040cdebf252d09e3bd2d30eb8.png
        assets/thumbnails/68695a84b68f544820f4adfdd9b3819c.jpg
        assets/thumbnails/76e0b087763e03c17d9176a2135491d0.png
        assets/thumbnails/7d426f203193bf76adc305cfe4bc81a6.png
        assets/thumbnails/820559963e349ba026fc5f4feeca0ac7.png
        assets/thumbnails/b4e819de0df6d32bcaf9fa5afde2ce10.jpg
        assets/thumbnails/b97d2e1a2048869febfe2ac1b08af87a.png
        assets/thumbnails/c4c287fa474f22da8898389364067e6f.png
        assets/thumbnails/cc93b0a77767fd70143e27a441a19885.jpg
        assets/thumbnails/f78d43d9a5253b67d3e0b155f1167de7.jpg
        assets/thumbnails/f86d0e44989fca5d01601c7a75841e3b.png

**Comment by ketai** [comment]
Yes, they seem to originate from a prior screen capture resolution.
